### ISSUE TITLE
Grunt-StripComments don`t stripping comment in CSS files

### ISSUE THREAD

**Issue by klierik** [kkemple/grunt-stripcomments#10]
Hello. Thanks for your module )

I try to use it in my project but it don`t work :(
code:
```
        comments: {
            css: {
                options: {
                    singleline: true,
                    multiline:  true
                },
                src: ['build/css/*.css']
            }
        },
```

run grunt result
```
grunt comments
Running "comments:css" (comments) task

Done, without errors.
```

And then in CSS files no changes :( Comments like:
`/* Extra small devices (phones, less than 768px) */`
or
`/*! normalize.css v3.0.1 | MIT License | git.io/normalize */`
steal present.

Also i try to change options value to:
```
singleline: false,
multiline:  false
```
but situation the same

**Comment by kkemple** [comment]
Resolved
