### ISSUE TITLE
Grunt-StripComments does NOT stripp comment in HTML files

### ISSUE THREAD

**Issue by andre-ferreira-qlik** [kkemple/grunt-stripcomments#11]
It would be a nice addition

**Comment by kkemple** [comment]
This would be a nice addition, I think there is a need for '#' style comment support as well

**Comment by kkemple** [comment]
i am cleaning up a lot of this code and adding tests, if you would like to tackle the HTML part feel free, it is my list though, I am just now getting back to this project I do apologize for it's incompleteness

**Comment by vitaly-t** [comment]
@andre-ferreira-qlik
[grunt-decomment](https://github.com/vitaly-t/grunt-decomment) can do it ;)

**Comment by Ryaaaan** [comment]
Does not work on Freemarker files (.ftl) :(
