### ISSUE TITLE
Regex for multiline comments

### ISSUE THREAD

**Issue by schiavassa** [kkemple/grunt-stripcomments#12]
The following regex worked better for my purposes:

```
var multilineComment = /\/\*[^*]*\*+([^\/*][^*]*\*+)*\//gm;
```

It allows me to strip comments from my .css and .scss files such as this:

```
/* ============================================================================
   @MASTER STYLESHEET
   ========================================================================= */
```

What do you think?

**Comment by freegenie** [comment]
I've got the same issue, I have a bounch of files filled with comments like this and right now they are not being cleaned up.

**Comment by kkemple** [comment]
This will be fixed by tonight, adding support for /* */ style comments, just writing some tests. This repo has had some major entropy due to my negligence but I finally have time to get it back up to a really solid place.

**Comment by kkemple** [comment]
resolved
