### ISSUE TITLE
Strip comments between /* & */

### ISSUE THREAD

**Issue by bennyn** [kkemple/grunt-stripcomments#15]
Hello, I like the idea of the plugin but for me it does not strip the following comments:

```javascript
  /*
  Abc
  
  Xyz
   */
```

Can you please add the feature to strip comments between `/*` & `*/`?

**Comment by kkemple** [comment]
This will be fixed by tonight, adding support for /* */ style comments, just writing some tests. This repo has had some major entropy due to my negligence but I finally have time to get it back up to a really solid place.

**Comment by kkemple** [comment]
resolved

**Comment by bennyn** [comment]
Thanks for helping out that quick! Works fine for me! :smiley:
