### ISSUE TITLE
line comments still exist after running.

### ISSUE THREAD

**Issue by dkomando** [kkemple/grunt-stripcomments#19]
Fails to remove comments like the following:
```
$scope.someObj.loaded = false; // Show when loaded.
$scope.someObj.loaded = false; /* Show when loaded. */
```

Maybe a slight update to the regEx? I have a working example broken out for my testing, although you may want to combine. Also, this is not thoroughly tested, granted I'm sure you unit tests will work that out.

```
module.exports = function(grunt, options) {
  const multilineComment   = /^[\t\s]*\/\*\*?[^!][\s\S]*?\*\/[\r\n]/gm;
  const multilineComment2  = /[\t\s]*\/\*\s[^\*\/]*\*\/[\t\s]*[\n\r]/g;
  const singleLineComment  = /^[\t\s]*(\/\/)[^\n\r]*[\n\r]/gm;
  const singleLineComment2 = /[\t\s]+\/\/\s[^\n]*\n/g;

	return function(file) {
		var contents = grunt.file.read(file);

		if (options.multiline) {
			contents = contents.replace(multilineComment,'').replace(multilineComment2,'\n');
		}

		if (options.singleline) {
			contents = contents.replace(singleLineComment,'').replace(singleLineComment2,'\n');
		}

		grunt.file.write(file, contents);
	};
};
```

**Comment by kkemple** [comment]
this is because it is too difficult to parse out regexs from comments without using ASTs. And at that point you can just use a more advanced tool, also, you can run the tests locally with `npm test` to see if it breaks regexs

**Comment by kkemple** [comment]
@dkomando any update on this? or should I close out this ticket? also, looking for someone to take this over if you are interested

**Comment by dkomando** [comment]
We can probably close this. 

I ended up just adding the regex from my initial comment to my local version, not the brightest way to do it but a quick and dirty solution.

I wish I could take this over, but I would not be able to dedicate any time to running the project properly. Which would probably be more of a disservice. 

However, I do want to say thanks for creating this project as it is still very helpful to me and used daily!

**Comment by kkemple** [comment]
no problem! thanks for the quick reply!
